### ISSUE TITLE
git for-each-ref

### ISSUE THREAD

**Issue by asayers** [lachlankrautz/git-who#1]
I know you probably don't want to hear this, but just FYI: git supports this functionality natively.

```ini
# ~/.gitconfig

[alias]
who = for-each-ref --sort=committerdate --sort=authorname --format='[%(committerdate:short)] %(align:25,left)%(authorname)%(end)%(refname:short)' refs/heads
```

Then you can even do `git who --no-merged master` to see unmerged branches, or `git who --contains 2.1.4` to see branches created since tag "2.1.4".

**Comment by lachlankrautz** [comment]
Nah that's cool, thanks for sharing.
